#include <catch2/catch_test_macros.hpp>

extern "C" {
#include <mach/mach.h>
// Generated by MIG from mach_exc.defs (see MachBug/cmake/MachBugMig.cmake).
// mach_exc.h here is mig's -sheader output: it is what actually declares
// mach_exc_server and the catch_* callback prototypes. The -header (user
// side) output is intentionally not generated -- see MachBugMig.cmake.
#include "mach_exc.h"
}

TEST_CASE("the MIG-generated exception server is available")
{
    // mach_exc_server is the dispatch routine the receive loop calls.
    // (Address-of, not a bare name: a bare function name is never null and
    // clang correctly flags that comparison as tautological. Taking its
    // address is what actually proves the symbol linked.)
    REQUIRE(&mach_exc_server != nullptr);
}

TEST_CASE("the exception server carries 64-bit exception codes")
{
    // mach_exception_data_t is the mach_ variant's payload type; exc.defs'
    // exception_data_t is 32-bit and would silently truncate an arm64
    // address. This is a compile-time check: it does not compile at all
    // against the 32-bit variant, whose catch_exception_raise* routines take
    // exception_data_t instead.
    exception_type_t exception = EXC_BAD_ACCESS;
    mach_exception_data_type_t code_storage[2] = {0, 0};
    mach_exception_data_t code = code_storage;
    (void)exception;
    (void)code;
    REQUIRE(sizeof(code_storage[0]) == sizeof(int64_t));
}
