// The exception loop: Start(), the four thread-safe commands, and the receive loop that turns
// Mach exception messages into cb*() callbacks. This is the file with no ElfBug counterpart --
// see the class comment at the top of Debugger.h for why ElfBug's waitpid()-shaped debugLoop()
// does not transfer here, and ExceptionServer.cpp for the MIG entry point that calls into
// handleException() below.
//
// mach_msg send/receive error codes are reported through mach_error_string() directly rather
// than Process::DescribeKernReturn(): that helper's KERN_FAILURE branch is deliberately worded
// for task_for_pid's most common failure (a missing get-task-allow entitlement) and would be
// misleading attached to a send/receive error that has nothing to do with entitlements.

#include <MachBug/core/Debugger.h>

#include <mach/mach_error.h>
#include <mach/thread_status.h>
#include <sys/wait.h>
#include <csignal>
#include <cerrno>
#include <cstring>

// Generated by MIG from mach_exc.defs (see MachBug/cmake/MachBugMig.cmake). Declares
// mach_exc_server, the dispatch routine that turns a raw exception message into a call to
// catch_mach_exception_raise_state_identity() (ExceptionServer.cpp) or one of its two
// never-used siblings (MachBugMigStubs.c).
extern "C" {
#include "mach_exc.h"
}

namespace
{
    // How often exceptionLoop() gives up waiting for a message and checks whether the child has
    // exited instead (see the comment on that check, below). Small enough that Start()'s callers
    // see an exit promptly; large enough not to spin the loop thread on a target that is doing
    // nothing.
    constexpr mach_msg_timeout_t kExitPollIntervalMs = 20;

    std::string describeMachMsg(const mach_msg_return_t mr)
    {
        std::string result = "mach_msg_return_t " + std::to_string(mr);
        if(const char* text = mach_error_string(mr))
        {
            result += " (";
            result += text;
            result += ")";
        }
        return result;
    }

    // Single-step support, used by StepInto(). This is a best-effort addition: no test in this
    // task's suite exercises it (the committed tests only ever Continue()), and the x86_64
    // branch has not been run on real hardware -- this development machine is arm64. Both
    // branches follow the standard pattern (arm64: MDSCR_EL1.SS via ARM_DEBUG_STATE64; x86_64:
    // EFLAGS.TF via x86_THREAD_STATE64), reading/writing the state directly on the reporting
    // thread port handleException() is handed, since THREAD_STATE_NONE was requested at
    // task_set_exception_ports time and so old_state/new_state in the exception message itself
    // are always empty.
#if defined(__arm64__) || defined(__aarch64__)
    bool setSingleStep(const mach_port_t thread, const bool enable)
    {
        arm_debug_state64_t state{};
        mach_msg_type_number_t count = ARM_DEBUG_STATE64_COUNT;
        if(thread_get_state(thread, ARM_DEBUG_STATE64, reinterpret_cast<thread_state_t>(&state),
                             &count) != KERN_SUCCESS)
            return false;

        if(enable)
            state.__mdscr_el1 |= 1ULL; // MDSCR_EL1 bit 0: SS (hardware single step)
        else
            state.__mdscr_el1 &= ~1ULL;

        return thread_set_state(thread, ARM_DEBUG_STATE64, reinterpret_cast<thread_state_t>(&state),
                                 ARM_DEBUG_STATE64_COUNT) == KERN_SUCCESS;
    }
#elif defined(__x86_64__)
    bool setSingleStep(const mach_port_t thread, const bool enable)
    {
        x86_thread_state64_t state{};
        mach_msg_type_number_t count = x86_THREAD_STATE64_COUNT;
        if(thread_get_state(thread, x86_THREAD_STATE64, reinterpret_cast<thread_state_t>(&state),
                             &count) != KERN_SUCCESS)
            return false;

        constexpr uint64_t kEflagsTrapFlag = 0x100;
        if(enable)
            state.__rflags |= kEflagsTrapFlag;
        else
            state.__rflags &= ~kEflagsTrapFlag;

        return thread_set_state(thread, x86_THREAD_STATE64, reinterpret_cast<thread_state_t>(&state),
                                 x86_THREAD_STATE64_COUNT) == KERN_SUCCESS;
    }
#else
    bool setSingleStep(mach_port_t, bool) { return false; }
#endif

    // Set only around exceptionLoop()'s own call into mach_exc_server(), and read only by
    // catch_mach_exception_raise_state_identity() (ExceptionServer.cpp) while that call is on
    // the stack -- MIG's dispatcher invokes the catch_* routine synchronously, on the same
    // thread, so a thread-local pointer identifies "which Debugger is this message for" without
    // needing a mutex-guarded port->Debugger* registry that every exception message would have
    // to take a lock to consult.
    thread_local MachBug::Debugger* tlsCurrentLoopDebugger = nullptr;
}

namespace MachBug
{
    Debugger* Debugger::Current()
    {
        return tlsCurrentLoopDebugger;
    }

    bool Debugger::Start()
    {
        if(!mProcess)
        {
            cbInternalError("Start() called with no launched process -- Init() must succeed first");
            return false;
        }

        if(mIsRunning.exchange(true, std::memory_order_acq_rel))
        {
            cbInternalError("Start() called while a debug loop is already running for this Debugger");
            return false;
        }

        mach_port_t exceptionPort = MACH_PORT_NULL;
        kern_return_t kr = mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &exceptionPort);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("mach_port_allocate failed: " + Process::DescribeKernReturn(kr));
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        kr = mach_port_insert_right(mach_task_self(), exceptionPort, exceptionPort,
                                     MACH_MSG_TYPE_MAKE_SEND);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("mach_port_insert_right failed: " + Process::DescribeKernReturn(kr));
            mach_port_deallocate(mach_task_self(), exceptionPort);
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        // Installed while mProcess->task is still suspended (Init() left it that way via
        // POSIX_SPAWN_START_SUSPENDED) -- the child has executed no instruction of its own yet,
        // so there is no window in which it could raise an exception before a port exists to
        // catch it. EXCEPTION_STATE_IDENTITY gives both the thread port and (if requested) its
        // state in one message; MACH_EXCEPTION_CODES is what makes the codes 64-bit, matching
        // mach_exc.defs over exc.defs (see MachBugMig.cmake). THREAD_STATE_NONE: this loop does
        // not need the thread's register state delivered in the message itself, since
        // handleException() is handed the thread's own port and can call thread_get_state() /
        // thread_set_state() on it directly when it needs to (see setSingleStep(), above).
        kr = task_set_exception_ports(
            mProcess->task,
            EXC_MASK_BREAKPOINT | EXC_MASK_BAD_ACCESS | EXC_MASK_BAD_INSTRUCTION |
                EXC_MASK_ARITHMETIC | EXC_MASK_SOFTWARE,
            exceptionPort,
            EXCEPTION_STATE_IDENTITY | MACH_EXCEPTION_CODES,
            THREAD_STATE_NONE);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("task_set_exception_ports failed: " + Process::DescribeKernReturn(kr));
            mach_port_deallocate(mach_task_self(), exceptionPort);
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        mExceptionPort = exceptionPort;

        cbCreateProcessEvent(mProcess->pid);

        // Only now -- ports installed -- is it safe to let the child execute. This resumes the
        // exact suspension Task 3's Init() created and its regression test
        // (debugger_launch.cpp, "a suspended launch produces no output until resumed") proves is
        // real; that test resumes the same way, by hand, for the same reason this one does it
        // for real: SIGCONT is what actually undoes POSIX_SPAWN_START_SUSPENDED, not
        // task_resume() (there is no extra task-level suspension from posix_spawn to undo here;
        // Pause()'s task_suspend()/task_resume() pairing below is a separate, later mechanism).
        if(kill(mProcess->pid, SIGCONT) != 0)
        {
            cbInternalError("SIGCONT failed to resume the suspended child: " +
                             std::string(strerror(errno)));
            mach_port_deallocate(mach_task_self(), mExceptionPort);
            mExceptionPort = MACH_PORT_NULL;
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        exceptionLoop();

        if(mExceptionPort != MACH_PORT_NULL)
        {
            mach_port_deallocate(mach_task_self(), mExceptionPort);
            mExceptionPort = MACH_PORT_NULL;
        }

        mIsRunning.store(false, std::memory_order_release);
        return true;
    }

    void Debugger::exceptionLoop()
    {
        struct MachMessage
        {
            mach_msg_header_t header;
            uint8_t body[512];
        };

        for(;;)
        {
            if(mStopRequested.load(std::memory_order_acquire) &&
               !mStopped.load(std::memory_order_acquire))
            {
                // Stop() was called while the target is free-running -- no thread is parked in
                // handleException() to hand a decision to, so there is no reply to withhold or
                // send. Tear the child down directly, the same way Terminate() does.
                break;
            }

            MachMessage request{};
            const mach_msg_return_t rcvResult = mach_msg(
                &request.header,
                MACH_RCV_MSG | MACH_RCV_TIMEOUT | MACH_RCV_INTERRUPT,
                0,
                sizeof(request),
                mExceptionPort,
                kExitPollIntervalMs,
                MACH_PORT_NULL);

            if(rcvResult == MACH_RCV_TIMED_OUT)
            {
                // No exception arrived in this slice. This is also the only place a *clean*
                // exit is ever noticed: exiting normally raises no Mach exception at all, so a
                // receive loop with nothing else in it would simply wait forever for a message
                // that is never coming. This process is the child's real parent (posix_spawn,
                // not an attach), so waitpid(WNOHANG) is a direct, reliable answer -- no
                // EXC_CRASH synthesis or dead-name/proc-exit notification needed for a debugger
                // that already owns the pid.
                int status = 0;
                const pid_t waited = mProcess ? waitpid(mProcess->pid, &status, WNOHANG) : -1;
                if(waited > 0)
                {
                    const int exitCode = WIFEXITED(status) ? WEXITSTATUS(status) : -WTERMSIG(status);
                    cbExitProcessEvent(exitCode);
                    break;
                }
                continue;
            }

            if(rcvResult == MACH_RCV_INTERRUPTED)
                continue;

            if(rcvResult != MACH_MSG_SUCCESS)
            {
                cbInternalError("mach_msg receive on the exception port failed: " +
                                 describeMachMsg(rcvResult));
                break;
            }

            MachMessage reply{};

            // handleException() (called synchronously from inside mach_exc_server(), via
            // catch_mach_exception_raise_state_identity() in ExceptionServer.cpp) does not
            // return until the user's decision is known -- see the class comment in Debugger.h.
            // Only once it does is `reply` complete and ready to send; that send is what
            // actually resumes the target thread.
            tlsCurrentLoopDebugger = this;
            const boolean_t handled = mach_exc_server(&request.header, &reply.header);
            tlsCurrentLoopDebugger = nullptr;

            if(!handled)
            {
                // A message arrived on this port that isn't one of mach_exc.defs' three
                // routines -- MIG's dispatcher leaves no valid reply to send in this case.
                cbInternalError("a message arrived on the exception port that mach_exc_server "
                                 "did not recognize");
                continue;
            }

            const mach_msg_return_t sendResult = mach_msg(
                &reply.header,
                MACH_SEND_MSG,
                reply.header.msgh_size,
                0,
                MACH_PORT_NULL,
                MACH_MSG_TIMEOUT_NONE,
                MACH_PORT_NULL);

            if(sendResult != MACH_MSG_SUCCESS)
            {
                cbInternalError("mach_msg send of the exception reply failed: " +
                                 describeMachMsg(sendResult));
                break;
            }

            if(mStopRequested.load(std::memory_order_acquire))
                break; // Stop() supplied the decision inside handleException(); the reply that
                       // resumed the reporting thread has gone out, so it is safe to kill now.
        }

        if(mStopRequested.load(std::memory_order_acquire) && mProcess)
        {
            kill(mProcess->pid, SIGKILL);
            int status = 0;
            waitpid(mProcess->pid, &status, 0);
        }
    }

    kern_return_t Debugger::handleException(const mach_port_t thread, const exception_type_t exception,
                                             const mach_exception_data_t code,
                                             const mach_msg_type_number_t codeCnt)
    {
        // This call IS the stop. Nothing resumes the reporting thread until this function
        // returns -- MIG's generated server sends the reply that does so only after this
        // callback comes back to it. So the classification/callback below must happen before
        // parking, and the park (the mCmdCv.wait() further down) is the entire reason the
        // target does not run again until Continue()/StepInto()/Stop() says so.

        const bool wasStepCompletion = mStepArmed;
        mStepArmed = false;
        if(wasStepCompletion)
            setSingleStep(thread, false); // disarm; re-armed below only if StepInto() is chosen again

        {
            std::lock_guard<std::mutex> lock(mCmdMutex);
            mStopped.store(true, std::memory_order_release);
            mPendingCommand = Command::None;
        }

        if(wasStepCompletion)
        {
            cbStep();
        }
        else if(!mSeenFirstStop)
        {
            mSeenFirstStop = true;
            cbSystemBreakpoint();
        }
        else
        {
            const uint64_t address = codeCnt >= 2 ? static_cast<uint64_t>(code[1]) : 0;
            cbException(static_cast<uint32_t>(exception), address);
        }

        Command decision;
        {
            std::unique_lock<std::mutex> lock(mCmdMutex);
            mCmdCv.wait(lock, [this] {
                return mPendingCommand != Command::None ||
                       mStopRequested.load(std::memory_order_acquire);
            });

            decision = mPendingCommand != Command::None ? mPendingCommand : Command::Stop;
            mPendingCommand = Command::None;
            mStopped.store(false, std::memory_order_release);
        }

        if(decision == Command::StepInto)
        {
            if(setSingleStep(thread, true))
            {
                mStepArmed = true;
            }
            else
            {
                cbInternalError("StepInto: failed to arm single-step on the reporting thread; "
                                 "continuing normally instead");
            }
        }

        // Returning KERN_SUCCESS is what tells the kernel this exception was handled and the
        // reporting thread should resume -- true for Continue and StepInto alike; the only
        // difference between them is whether setSingleStep() armed the trap flag just above, not
        // the return code. Stop() takes the same return here (the thread must still be let go,
        // its message answered) and is instead handled by exceptionLoop() killing the child once
        // this reply has gone out; see its comment.
        return KERN_SUCCESS;
    }

    void Debugger::Continue()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        if(mStopped.load(std::memory_order_acquire))
        {
            mPendingCommand = Command::Continue;
            mCmdCv.notify_all();
        }
        else if(mPausedByUser.exchange(false, std::memory_order_acq_rel) && mProcess)
        {
            // Nothing is parked in handleException() -- the target was free-running when
            // Pause() task_suspended it directly, so undo that the same way, with task_resume().
            task_resume(mProcess->task);
        }
    }

    void Debugger::StepInto()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        if(mStopped.load(std::memory_order_acquire))
        {
            mPendingCommand = Command::StepInto;
            mCmdCv.notify_all();
        }
        // Nothing to single-step from if the target is free-running (Pause()'d or otherwise) --
        // there is no thread parked in handleException() to arm a step in.
    }

    void Debugger::Pause()
    {
        if(!mProcess)
            return;

        if(mStopped.load(std::memory_order_acquire))
            return; // already stopped at an exception; nothing more to pause

        if(task_suspend(mProcess->task) == KERN_SUCCESS)
            mPausedByUser.store(true, std::memory_order_release);
    }

    void Debugger::Stop()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        mStopRequested.store(true, std::memory_order_release);
        if(mStopped.load(std::memory_order_acquire))
            mPendingCommand = Command::Stop;
        mCmdCv.notify_all();
    }

    bool Debugger::IsStopped() const
    {
        return mStopped.load(std::memory_order_acquire) ||
               mPausedByUser.load(std::memory_order_acquire);
    }

    bool Debugger::IsRunning() const
    {
        return mIsRunning.load(std::memory_order_acquire);
    }

    void Debugger::cbCreateProcessEvent(pid_t) {}
    void Debugger::cbExitProcessEvent(int) {}
    void Debugger::cbSystemBreakpoint() {}
    void Debugger::cbStep() {}
    void Debugger::cbException(uint32_t, uint64_t) {}
}
