// The exception loop: Start(), the four thread-safe commands, and the receive loop that turns
// Mach exception messages into cb*() callbacks. This is the file with no ElfBug counterpart --
// see the class comment at the top of Debugger.h for why ElfBug's waitpid()-shaped debugLoop()
// does not transfer here, and ExceptionServer.cpp for the MIG entry point that calls into
// handleException() below.
//
// mach_msg send/receive error codes are reported through mach_error_string() directly rather
// than Process::DescribeKernReturn(): that helper's KERN_FAILURE branch is deliberately worded
// for task_for_pid's most common failure (a missing get-task-allow entitlement) and would be
// misleading attached to a send/receive error that has nothing to do with entitlements.

#include <MachBug/arch/Arch.h>
#include <MachBug/core/Debugger.h>

#include <mach/mach_error.h>
#include <mach/thread_status.h>
#include <sys/ptrace.h>
#include <sys/wait.h>
#include <csignal>
#include <cerrno>
#include <cstring>

// ARM_THREAD_STATE64 / x86_THREAD_STATE64 (see kExceptionPortStateFlavor, below) already reach
// this file transitively through <mach/thread_status.h> -> <mach/machine/thread_status.h> ->
// <mach/arm/thread_status.h> or <mach/i386/thread_status.h>, picked by the same architecture
// macros used here. These direct includes are redundant but make that dependency explicit rather
// than implicit in a transitive header chain.
#if defined(__x86_64__)
#include <mach/i386/thread_status.h>
#elif defined(__arm64__) || defined(__aarch64__)
#include <mach/arm/thread_status.h>
#endif

// Generated by MIG from mach_exc.defs (see MachBug/cmake/MachBugMig.cmake). Declares
// mach_exc_server, the dispatch routine that turns a raw exception message into a call to
// catch_mach_exception_raise_state_identity() (ExceptionServer.cpp) or one of its two
// never-used siblings (MachBugMigStubs.c).
extern "C" {
#include "mach_exc.h"
}

namespace
{
    // How often exceptionLoop() gives up waiting for a message and checks whether the child has
    // exited instead (see the comment on that check, below). Small enough that Start()'s callers
    // see an exit promptly; large enough not to spin the loop thread on a target that is doing
    // nothing.
    constexpr mach_msg_timeout_t kExitPollIntervalMs = 20;

    // task_set_exception_ports()'s flavor argument is not optional whenever the requested
    // behavior carries EXCEPTION_STATE (EXCEPTION_STATE_IDENTITY does): THREAD_STATE_NONE is
    // only valid for plain EXCEPTION_DEFAULT. An earlier version of this file passed
    // THREAD_STATE_NONE here regardless, on the reasoning that this loop never reads old_state
    // (THREAD_STATE_NONE) and never asks the reply to modify it -- a state flavor is
    // installed anyway because a *stated* flavor of NONE with a state-carrying behavior is not
    // "no state, that's fine," it is invalid input the kernel silently declines to act on: no
    // exception is ever delivered, and it falls through to default handling (a plain BSD signal
    // to the target) as if no port were registered at all. The one-argument diagnosis cost real
    // time (see the task report); the fix is to pick a real flavor and simply not use the state
    // it carries, which is exactly what handleException() already does (old_state is unread,
    // new_stateCnt is always set to 0 so the reply never asks to modify it).
    //
    // Picked by architecture rather than hardcoded to this development machine's arm64, since
    // x86_64 is in scope from Milestone 3 onward. Both are full general-register state flavors --
    // the same ones MachBug::arch's SetSingleStep() reads/writes directly via
    // thread_get_state()/thread_set_state() on the reporting thread's own port, though that call is independent of
    // what flavor the exception PORT itself is configured to describe state as.
#if defined(__x86_64__)
    constexpr thread_state_flavor_t kExceptionPortStateFlavor = x86_THREAD_STATE64;
#elif defined(__arm64__) || defined(__aarch64__)
    constexpr thread_state_flavor_t kExceptionPortStateFlavor = ARM_THREAD_STATE64;
#else
#error "MachBug's exception loop needs a real thread-state flavor for this architecture"
#endif

    std::string describeMachMsg(const mach_msg_return_t mr)
    {
        std::string result = "mach_msg_return_t " + std::to_string(mr);
        if(const char* text = mach_error_string(mr))
        {
            result += " (";
            result += text;
            result += ")";
        }
        return result;
    }

    // Single-step support, used by StepInto(). This is a best-effort addition: no test in this
    // task's suite exercises it (the committed tests only ever Continue()), and the x86_64
    // branch has not been run on real hardware -- this development machine is arm64. Both
    // branches follow the standard pattern (arm64: MDSCR_EL1.SS via ARM_DEBUG_STATE64; x86_64:
    // EFLAGS.TF via x86_THREAD_STATE64), reading/writing the state directly on the reporting
    // thread port handleException() is handed, via a *different* state flavor
    // (ARM_DEBUG_STATE64/x86_THREAD_STATE64 here) than kExceptionPortStateFlavor configures the
    // exception message itself to carry -- the two are independent: this loop never reads the
    // old_state/new_state the message carries (handleException() ignores them and always
    // reports new_stateCnt = 0, meaning "unmodified"), so it does not matter that they are a
    // different flavor than what these functions ask thread_get_state()/thread_set_state() for
    // directly.
// The host's architecture, for the arch-layer calls below. The engine has no architecture query
// of its own at this level -- that is the C API's GetArch(), which also handles a translated
// target -- and this loop only ever touches the thread state of a target it is natively
// debugging, so the host's own architecture is the right answer here.
#if defined(__arm64__) || defined(__aarch64__)
    constexpr DbgArch kLoopArch = DbgArch_Arm64;
#elif defined(__x86_64__)
    constexpr DbgArch kLoopArch = DbgArch_X86_64;
#else
    constexpr DbgArch kLoopArch = DbgArch_Unknown;
#endif

    // Set only around exceptionLoop()'s own call into mach_exc_server(), and read only by
    // catch_mach_exception_raise_state_identity() (ExceptionServer.cpp) while that call is on
    // the stack -- MIG's dispatcher invokes the catch_* routine synchronously, on the same
    // thread, so a thread-local pointer identifies "which Debugger is this message for" without
    // needing a mutex-guarded port->Debugger* registry that every exception message would have
    // to take a lock to consult.
    thread_local MachBug::Debugger* tlsCurrentLoopDebugger = nullptr;
}

namespace MachBug
{
    Debugger* Debugger::Current()
    {
        return tlsCurrentLoopDebugger;
    }

    bool Debugger::Start()
    {
        if(!mProcess)
        {
            cbInternalError("Start() called with no launched process -- Init() must succeed first");
            return false;
        }

        if(mIsRunning.exchange(true, std::memory_order_acq_rel))
        {
            cbInternalError("Start() called while a debug loop is already running for this Debugger");
            return false;
        }

        // A fresh Init() launching a new child after a previous one's Start() ended (naturally,
        // or via Stop()) is the normal way to reuse a Debugger object, and every run of this loop
        // needs to begin without the previous one's bookkeeping still attached -- most pointedly
        // mStopRequested, which Stop() sets permanently and nothing previously cleared: a second
        // Start() after a Stop()'d first one would otherwise see it already true and return
        // (by way of exceptionLoop()'s own top-of-loop check) before installing a single port.
        mStopRequested.store(false, std::memory_order_release);
        mStopped.store(false, std::memory_order_release);
        mPausedByUser.store(false, std::memory_order_release);
        mSeenFirstStop = false;
        mStepArmed = false;

        // task_set_exception_ports() alone only ever catches an exception the target's own
        // execution triggers directly (a hardware fault, a trap instruction) -- it has no effect
        // on ordinary BSD signal delivery to the child. Without this call, a completely
        // well-behaved target (one that never faults) raises no exception in its entire life:
        // resuming it below via SIGCONT would just let it run straight through, with nothing to
        // report a first stop from. PT_ATTACHEXC is what changes that: it marks this task as a
        // Mach-exception-based tracer of the child (mirroring what PTRACE_TRACEME + the kernel's
        // automatic post-exec SIGTRAP does for ElfBug, just reached from the opposite side and
        // through the exception port instead of a bare signal) and, critically, makes the
        // kernel route every signal the child would otherwise receive -- including the very
        // SIGCONT this function sends a few lines down to undo Init()'s
        // POSIX_SPAWN_START_SUSPENDED -- through the exception port as EXC_SOFTWARE/
        // EXC_SOFT_SIGNAL instead of delivering it directly. That SIGCONT-turned-exception is
        // what becomes the first exception handleException() ever sees and reports through
        // cbSystemBreakpoint(): replying to it (Continue()) is what lets the original SIGCONT
        // actually take effect and the child run for the first time. Must happen before the
        // task_set_exception_ports() call below has any chance to matter, and while the child is
        // still suspended -- same reasoning as installing the exception ports themselves early.
        //
        // Skipped when Attach() (Debugger.cpp) already made this exact call: ptrace(2) does not
        // allow attaching to an already-attached pid a second time (EBUSY), and there is nothing
        // this second call would add -- Attach() already put mProcess->pid in the state this one
        // exists to reach (a Mach-exception tracee of this process), by the same call, before
        // ever returning to its own caller.
        if(!mAttachedViaPtrace && ptrace(PT_ATTACHEXC, mProcess->pid, nullptr, 0) != 0)
        {
            cbInternalError("ptrace(PT_ATTACHEXC) failed for pid " +
                             std::to_string(mProcess->pid) + ": " + std::string(strerror(errno)));
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        mach_port_t exceptionPort = MACH_PORT_NULL;
        kern_return_t kr = mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &exceptionPort);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("mach_port_allocate failed: " + Process::DescribeKernReturn(kr));
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        kr = mach_port_insert_right(mach_task_self(), exceptionPort, exceptionPort,
                                     MACH_MSG_TYPE_MAKE_SEND);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("mach_port_insert_right failed: " + Process::DescribeKernReturn(kr));
            mach_port_deallocate(mach_task_self(), exceptionPort);
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        // Installed while mProcess->task is still suspended (Init() left it that way via
        // POSIX_SPAWN_START_SUSPENDED) -- the child has executed no instruction of its own yet,
        // so there is no window in which it could raise an exception before a port exists to
        // catch it. EXCEPTION_STATE_IDENTITY gives both the thread port and its state in one
        // message; MACH_EXCEPTION_CODES is what makes the codes 64-bit, matching mach_exc.defs
        // over exc.defs (see MachBugMig.cmake). The flavor (kExceptionPortStateFlavor, above)
        // must be a real one -- EXCEPTION_STATE_IDENTITY is a state-carrying behavior, and
        // THREAD_STATE_NONE is only valid for EXCEPTION_DEFAULT; passing it here does not mean
        // "no state, that's fine," it means the kernel silently declines to deliver anything at
        // all. This loop still never reads the state the message carries (handleException() is
        // handed the thread's own port and calls thread_get_state()/thread_set_state() on it
        // directly when it needs to -- see MachBug::arch::SetSingleStep()) -- it just cannot ask for
        // *zero* state and expect delivery to still happen.
        kr = task_set_exception_ports(
            mProcess->task,
            EXC_MASK_BREAKPOINT | EXC_MASK_BAD_ACCESS | EXC_MASK_BAD_INSTRUCTION |
                EXC_MASK_ARITHMETIC | EXC_MASK_SOFTWARE,
            exceptionPort,
            EXCEPTION_STATE_IDENTITY | MACH_EXCEPTION_CODES,
            kExceptionPortStateFlavor);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("task_set_exception_ports failed: " + Process::DescribeKernReturn(kr));
            mach_port_deallocate(mach_task_self(), exceptionPort);
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        mExceptionPort = exceptionPort;

        cbCreateProcessEvent(mProcess->pid);

        // Only now -- ports installed -- is it safe to let the child execute. This resumes the
        // exact suspension Task 3's Init() created and its regression test
        // (debugger_launch.cpp, "a suspended launch produces no output until resumed") proves is
        // real; that test resumes the same way, by hand, for the same reason this one does it
        // for real: SIGCONT is what actually undoes POSIX_SPAWN_START_SUSPENDED, not
        // task_resume() (there is no extra task-level suspension from posix_spawn to undo here;
        // Pause()'s task_suspend()/task_resume() pairing below is a separate, later mechanism).
        //
        // The same call does the equivalent job on the attach path (Debugger::Attach()): its own
        // PT_ATTACHEXC also stops the target via an actual SIGSTOP (ptrace(2)), which this SIGCONT
        // undoes exactly as it does POSIX_SPAWN_START_SUSPENDED's -- and since Attach() already
        // made pid a Mach-exception tracee of this process before this point, the kernel routes
        // this SIGCONT through mExceptionPort just installed above, the same way it does for a
        // launched child. Task 6 introduced Attach(); this call needed no change for it to work.
        if(kill(mProcess->pid, SIGCONT) != 0)
        {
            cbInternalError("SIGCONT failed to resume the suspended child: " +
                             std::string(strerror(errno)));
            mach_port_deallocate(mach_task_self(), mExceptionPort);
            mExceptionPort = MACH_PORT_NULL;
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        exceptionLoop();

        if(mExceptionPort != MACH_PORT_NULL)
        {
            mach_port_deallocate(mach_task_self(), mExceptionPort);
            mExceptionPort = MACH_PORT_NULL;
        }

        mIsRunning.store(false, std::memory_order_release);
        return true;
    }

    void Debugger::exceptionLoop()
    {
        // Sized from mach_exc.h's own generated request/reply unions, not a guessed constant:
        // __Reply__mach_exception_raise_state_t's new_state[1296] alone is close to 5KB once the
        // other exception_raise_state* variants sharing this subsystem's message ID range are
        // accounted for. A hand-picked buffer (512 bytes, this file's first draft) is smaller
        // than that and risks MACH_RCV_TOO_LARGE -- which also destroys the oversized message,
        // rather than merely truncating it. This is not a theoretical case any more than it was
        // when this comment was first written: kExceptionPortStateFlavor (above) is a real state
        // flavor now, so the request genuinely does carry old_state (a modest few hundred bytes
        // for ARM_THREAD_STATE64/x86_THREAD_STATE64, well under the union's worst case) --
        // handleException() still ignores it and always reports new_stateCnt = 0, so the reply
        // itself carries none, but sizing this from the generated union rather than a guess means
        // neither direction depends on that staying true.
        union RequestMessage
        {
            mach_msg_header_t header;
            __RequestUnion__catch_mach_exc_subsystem body;
        };
        union ReplyMessage
        {
            mach_msg_header_t header;
            __ReplyUnion__catch_mach_exc_subsystem body;
        };

        for(;;)
        {
            if(mStopRequested.load(std::memory_order_acquire) &&
               !mStopped.load(std::memory_order_acquire))
            {
                // Stop() was called while the target is free-running -- no thread is parked in
                // handleException() to hand a decision to, so there is no reply to withhold or
                // send. Tear the child down directly, the same way Terminate() does.
                break;
            }

            RequestMessage request{};
            const mach_msg_return_t rcvResult = mach_msg(
                &request.header,
                MACH_RCV_MSG | MACH_RCV_TIMEOUT | MACH_RCV_INTERRUPT,
                0,
                sizeof(request),
                mExceptionPort,
                kExitPollIntervalMs,
                MACH_PORT_NULL);

            if(rcvResult == MACH_RCV_TIMED_OUT)
            {
                // No exception arrived in this slice. This is also the only place a *clean*
                // exit is ever noticed: exiting normally raises no Mach exception at all, so a
                // receive loop with nothing else in it would simply wait forever for a message
                // that is never coming. This process is the child's real parent (posix_spawn,
                // not an attach), so waitpid(WNOHANG) is a direct, reliable answer -- no
                // EXC_CRASH synthesis or dead-name/proc-exit notification needed for a debugger
                // that already owns the pid.
                //
                // waited > 0 alone is not enough, though: this pid was ptrace(PT_ATTACHEXC)'d
                // above (see Start()), and a traced child reports ordinary ptrace stops through
                // waitpid() too -- for instance while a thread is parked on an unanswered
                // exception reply, which is not a rare timing accident here, it is this loop's
                // own normal operation. Treating any waitpid() return as an exit, unconditionally,
                // computed a bogus exit code from a WIFSTOPPED status (WIFEXITED false ->
                // -WTERMSIG() of whatever bits happen to be set) and announced a live target as
                // dead. Process::IsRealExit() is the predicate that was missing.
                int status = 0;
                const pid_t waited = mProcess ? waitpid(mProcess->pid, &status, WNOHANG) : -1;
                if(waited > 0 && Process::IsRealExit(status))
                {
                    cbExitProcessEvent(Process::ExitCodeFromStatus(status));
                    break;
                }
                continue;
            }

            if(rcvResult == MACH_RCV_INTERRUPTED)
                continue;

            if(rcvResult != MACH_MSG_SUCCESS)
            {
                cbInternalError("mach_msg receive on the exception port failed: " +
                                 describeMachMsg(rcvResult));
                break;
            }

            ReplyMessage reply{};

            // handleException() (called synchronously from inside mach_exc_server(), via
            // catch_mach_exception_raise_state_identity() in ExceptionServer.cpp) does not
            // return until the user's decision is known -- see the class comment in Debugger.h.
            // Only once it does is `reply` complete and ready to send; that send is what
            // actually resumes the target thread.
            tlsCurrentLoopDebugger = this;
            const boolean_t handled = mach_exc_server(&request.header, &reply.header);
            tlsCurrentLoopDebugger = nullptr;

            if(!handled)
            {
                // A message arrived on this port that isn't one of mach_exc.defs' three
                // routines -- MIG's dispatcher leaves no valid reply to send in this case.
                cbInternalError("a message arrived on the exception port that mach_exc_server "
                                 "did not recognize");
                continue;
            }

            const mach_msg_return_t sendResult = mach_msg(
                &reply.header,
                MACH_SEND_MSG,
                reply.header.msgh_size,
                0,
                MACH_PORT_NULL,
                MACH_MSG_TIMEOUT_NONE,
                MACH_PORT_NULL);

            if(sendResult != MACH_MSG_SUCCESS)
            {
                cbInternalError("mach_msg send of the exception reply failed: " +
                                 describeMachMsg(sendResult));
                break;
            }

            if(mStopRequested.load(std::memory_order_acquire))
                break; // Stop() supplied the decision inside handleException(); the reply that
                       // resumed the reporting thread has gone out, so it is safe to kill now.

            // Only here, after the send succeeded and with no teardown pending, is the target
            // actually running again -- see cbResumed()'s comment in Debugger.h.
            cbResumed();
        }

        if(mStopRequested.load(std::memory_order_acquire) && mProcess)
        {
            // Process::DetachAndKill(), not a bare kill()+waitpid(): this pid is still
            // ptrace(PT_ATTACHEXC)'d (Start(), above), and this is the one place in this class
            // that is guaranteed to be reached with nobody left servicing the exception port --
            // the receive loop above has already broken out of. A plain SIGKILL sent here is
            // routed through that port exactly like any other signal and, unanswered, never takes
            // effect: not slower, not at all. Reproduced 3/3 with the documented sequence (Init ->
            // Start -> answer the first stop with Continue -> Stop) before this fix; see
            // Process::DetachAndKill()'s comment in Process.h.
            Process::DetachAndKill(mProcess->pid, nullptr);
        }
    }

    kern_return_t Debugger::handleException(const mach_port_t thread, const exception_type_t exception,
                                             const mach_exception_data_t code,
                                             const mach_msg_type_number_t codeCnt)
    {
        // This call IS the stop. Nothing resumes the reporting thread until this function
        // returns -- MIG's generated server sends the reply that does so only after this
        // callback comes back to it. So the classification/callback below must happen before
        // parking, and the park (the mCmdCv.wait() further down) is the entire reason the
        // target does not run again until Continue()/StepInto()/Stop() says so.

        const bool wasStepCompletion = mStepArmed;
        mStepArmed = false;
        if(wasStepCompletion)
        {
            // Disarmed through the arch layer (arch/Arm64.cpp, arch/X86_64.cpp) rather than here;
            // re-armed below only if StepInto() is chosen again.
            std::string stepError;
            if(!arch::SetSingleStep(kLoopArch, thread, false, &stepError))
                cbInternalError(stepError);
        }

        // EXC_SOFTWARE with code[0] == EXC_SOFT_SIGNAL is how PT_ATTACHEXC (Start(), above)
        // routes an ordinary BSD signal through this port instead of delivering it directly;
        // code[1] carries the signal number. The very first exception this loop ever sees is
        // deliberately treated as the target's first stop regardless of what kind it is (see the
        // !mSeenFirstStop branch, below) -- in practice that first one always is this case, since
        // it is the SIGCONT Start() sends to undo POSIX_SPAWN_START_SUSPENDED, turned into an
        // exception by the same PT_ATTACHEXC. A *second* SIGCONT has also been observed arriving
        // later (roughly one run in ten), and unlike the first one, nothing in this milestone's
        // contract gives a caller any way to have asked to be notified of it -- routing it to
        // cbException() and parking the way a real debug exception parks left the reporting
        // thread waiting for a Continue() call nobody knew to make, IsStopped() still reporting
        // false throughout, and the target hung forever with the reply withheld.
        //
        // The fix is deliberately narrow: only SIGCONT is absorbed, and only code[1] == SIGCONT
        // decides that, not code[0] alone. An earlier version of this check matched any
        // EXC_SOFT_SIGNAL regardless of which signal, which silently passed through *every*
        // signal-passthrough exception -- a target's own abort() (SIGABRT) or a user's SIGINT
        // would have been swallowed exactly like SIGCONT, with no cbException() call, no stop, and
        // no way for a caller to ever know it happened. That is worse than the hang it was fixing:
        // a hang is at least visible. SIGCONT is the one signal this loop's own machinery can
        // cause to arrive here more than once and the only one that did not originate from the
        // target or its user in the first place -- it originated from this debugger's own resume
        // handshake -- so it is the only one with a defensible reason to be answered without ever
        // being reported. Every other signal-passthrough exception now falls through to the
        // ordinary cbException() path below, exactly as any other exception this loop does not
        // have more specific handling for yet.
        constexpr int32_t kExcSoftSignal = 0x10003; // EXC_SOFT_SIGNAL
        const bool isSignalPassthrough =
            exception == EXC_SOFTWARE && codeCnt >= 2 && code[0] == kExcSoftSignal &&
            code[1] == SIGCONT;

        if(!wasStepCompletion && mSeenFirstStop && isSignalPassthrough)
            return KERN_SUCCESS;

        {
            std::lock_guard<std::mutex> lock(mCmdMutex);
            // Recorded before mStopped, not after: IsStopped() going true is what tells another
            // thread there are registers to read, so the thread they belong to has to be
            // readable by the time that is observable.
            mStoppedThread.store(thread, std::memory_order_release);
            mStopped.store(true, std::memory_order_release);
            mPendingCommand = Command::None;
        }

        if(wasStepCompletion)
        {
            cbStep();
        }
        else if(!mSeenFirstStop)
        {
            mSeenFirstStop = true;
            cbSystemBreakpoint();
        }
        else
        {
            const uint64_t address = codeCnt >= 2 ? static_cast<uint64_t>(code[1]) : 0;
            cbException(static_cast<uint32_t>(exception), address);
        }

        Command decision;
        {
            std::unique_lock<std::mutex> lock(mCmdMutex);
            mCmdCv.wait(lock, [this] {
                return mPendingCommand != Command::None ||
                       mStopRequested.load(std::memory_order_acquire);
            });

            decision = mPendingCommand != Command::None ? mPendingCommand : Command::Stop;
            mPendingCommand = Command::None;
            mStopped.store(false, std::memory_order_release);
            // Cleared with the stop it belonged to: a caller that reads registers from a thread
            // that is running again gets a torn answer, and no error to tell it so.
            mStoppedThread.store(MACH_PORT_NULL, std::memory_order_release);
        }

        if(decision == Command::StepInto)
        {
            std::string armError;
            if(arch::SetSingleStep(kLoopArch, thread, true, &armError))
            {
                mStepArmed = true;
            }
            else
            {
                cbInternalError("StepInto: failed to arm single-step on the reporting thread; "
                                 "continuing normally instead");
            }
        }

        // Returning KERN_SUCCESS is what tells the kernel this exception was handled and the
        // reporting thread should resume -- true for Continue and StepInto alike; the only
        // difference between them is whether SetSingleStep() armed the trap flag just above, not
        // the return code. Stop() takes the same return here (the thread must still be let go,
        // its message answered) and is instead handled by exceptionLoop() killing the child once
        // this reply has gone out; see its comment.
        return KERN_SUCCESS;
    }

    void Debugger::Continue()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);

        // Independent ifs, not if/else: mStopped (a parked exception reply) and mPausedByUser (a
        // direct task_suspend()) are two separate reasons the target might not be running, and --
        // under a race Pause() used to allow (see its own comment) -- could in principle both be
        // true at once. A single Continue() call clears whichever of them apply, rather than
        // leaving the other stranded until a second call happens to be made because IsStopped()
        // still (correctly) said so.
        if(mStopped.load(std::memory_order_acquire))
        {
            mPendingCommand = Command::Continue;
            mCmdCv.notify_all();
        }
        if(mPausedByUser.exchange(false, std::memory_order_acq_rel) && mProcess)
        {
            // Nothing is parked in handleException() -- the target was free-running when
            // Pause() task_suspended it directly, so undo that the same way, with task_resume().
            task_resume(mProcess->task);
        }
    }

    void Debugger::StepInto()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        if(mStopped.load(std::memory_order_acquire))
        {
            mPendingCommand = Command::StepInto;
            mCmdCv.notify_all();
        }
        // Nothing to single-step from if the target is free-running (Pause()'d or otherwise) --
        // there is no thread parked in handleException() to arm a step in.
    }

    void Debugger::Pause()
    {
        if(!mProcess)
            return;

        // The whole check-then-act sequence below holds mCmdMutex so it cannot interleave with
        // handleException() setting mStopped=true (which happens under the same lock): either
        // this runs first (sees mStopped false, may go on to task_suspend()) or the exception's
        // own mStopped=true happens first (this then sees it and returns). Checking mStopped
        // outside this lock, as an earlier version of this function did, raced exactly that
        // transition: Pause() could read false, then task_suspend() a target that had, in the
        // meantime, already become parked at a genuine exception -- suspending an
        // already-stopped task and setting mPausedByUser regardless.
        std::lock_guard<std::mutex> lock(mCmdMutex);

        if(mPausedByUser.load(std::memory_order_acquire))
            return; // already paused -- idempotent, so repeated Pause() calls cannot leave
                     // task_suspend()'s internal count deeper than the one task_resume() a
                     // Continue() call will later issue; the alternative (suspending again on
                     // every call) is exactly the "Pause(); Pause(); Continue();" bug this
                     // guards against: two suspends, only one resume, permanently stuck.

        if(mStopped.load(std::memory_order_acquire))
            return; // already stopped at an exception; nothing more to pause

        if(task_suspend(mProcess->task) == KERN_SUCCESS)
            mPausedByUser.store(true, std::memory_order_release);
    }

    void Debugger::Stop()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        mStopRequested.store(true, std::memory_order_release);
        if(mStopped.load(std::memory_order_acquire))
            mPendingCommand = Command::Stop;
        mCmdCv.notify_all();
    }

    bool Debugger::IsStopped() const
    {
        return mStopped.load(std::memory_order_acquire) ||
               mPausedByUser.load(std::memory_order_acquire);
    }

    bool Debugger::IsRunning() const
    {
        return mIsRunning.load(std::memory_order_acquire);
    }

    mach_port_t Debugger::StoppedThread() const
    {
        return mStoppedThread.load(std::memory_order_acquire);
    }

    mach_port_t Debugger::ResolveThread(const uint64_t threadId) const
    {
        if(threadId == 0)
            return StoppedThread();

        const auto candidate = static_cast<mach_port_t>(threadId);
        if(!mProcess || mProcess->task == MACH_PORT_NULL)
            return MACH_PORT_NULL;

        // Checked against the task's actual thread list rather than trusted: a caller handing
        // over a stale port from a previous stop, or an outright invented number, would
        // otherwise reach thread_get_state, which reports KERN_INVALID_ARGUMENT for a port that
        // is not a thread and MACH_SEND_INVALID_DEST for one that is not even a port. Neither
        // says "no such thread", which is what actually happened.
        //
        // This is not thread enumeration: nothing here lists threads for a caller, and every
        // port task_threads hands over is released in the same loop.
        thread_act_array_t threads = nullptr;
        mach_msg_type_number_t count = 0;
        if(task_threads(mProcess->task, &threads, &count) != KERN_SUCCESS)
            return MACH_PORT_NULL;

        mach_port_t found = MACH_PORT_NULL;
        for(mach_msg_type_number_t i = 0; i < count; ++i)
        {
            if(threads[i] == candidate)
                found = candidate;
            mach_port_deallocate(mach_task_self(), threads[i]);
        }
        vm_deallocate(mach_task_self(), reinterpret_cast<vm_address_t>(threads),
                      count * sizeof(thread_act_t));
        return found;
    }

    void Debugger::cbCreateProcessEvent(pid_t) {}
    void Debugger::cbExitProcessEvent(int) {}
    void Debugger::cbSystemBreakpoint() {}
    void Debugger::cbResumed() {}
    void Debugger::cbStep() {}
    void Debugger::cbException(uint32_t, uint64_t) {}
}
