// The exception loop: Start(), the four thread-safe commands, and the receive loop that turns
// Mach exception messages into cb*() callbacks. This is the file with no ElfBug counterpart --
// see the class comment at the top of Debugger.h for why ElfBug's waitpid()-shaped debugLoop()
// does not transfer here, and ExceptionServer.cpp for the MIG entry point that calls into
// handleException() below.
//
// mach_msg send/receive error codes are reported through mach_error_string() directly rather
// than Process::DescribeKernReturn(): that helper's KERN_FAILURE branch is deliberately worded
// for task_for_pid's most common failure (a missing get-task-allow entitlement) and would be
// misleading attached to a send/receive error that has nothing to do with entitlements.

#include <MachBug/arch/Arch.h>
#include <MachBug/core/Debugger.h>

#include <mach/mach_error.h>
#include <mach/thread_status.h>
#include <sys/ptrace.h>
#include <sys/wait.h>
#include <csignal>
#include <cerrno>
#include <cstring>

// ARM_THREAD_STATE64 / x86_THREAD_STATE64 (see kExceptionPortStateFlavor, below) already reach
// this file transitively through <mach/thread_status.h> -> <mach/machine/thread_status.h> ->
// <mach/arm/thread_status.h> or <mach/i386/thread_status.h>, picked by the same architecture
// macros used here. These direct includes are redundant but make that dependency explicit rather
// than implicit in a transitive header chain.
#if defined(__x86_64__)
#include <mach/i386/thread_status.h>
#elif defined(__arm64__) || defined(__aarch64__)
#include <mach/arm/thread_status.h>
#endif

// Generated by MIG from mach_exc.defs (see MachBug/cmake/MachBugMig.cmake). Declares
// mach_exc_server, the dispatch routine that turns a raw exception message into a call to
// catch_mach_exception_raise_state_identity() (ExceptionServer.cpp) or one of its two
// never-used siblings (MachBugMigStubs.c).
extern "C" {
#include "mach_exc.h"
}

namespace
{
    // How often exceptionLoop() gives up waiting for a message and checks whether the child has
    // exited instead (see the comment on that check, below). Small enough that Start()'s callers
    // see an exit promptly; large enough not to spin the loop thread on a target that is doing
    // nothing.
    constexpr mach_msg_timeout_t kExitPollIntervalMs = 20;

    // The exceptions this engine asks for. Named once because the teardown has to hand the same
    // set back, and a release that covers less than the install leaves a port registered for
    // exceptions nobody is going to answer.
    constexpr exception_mask_t kExceptionMask =
        EXC_MASK_BREAKPOINT | EXC_MASK_BAD_ACCESS | EXC_MASK_BAD_INSTRUCTION |
        EXC_MASK_ARITHMETIC | EXC_MASK_SOFTWARE;

    // task_set_exception_ports()'s flavor argument is not optional whenever the requested
    // behavior carries EXCEPTION_STATE (EXCEPTION_STATE_IDENTITY does): THREAD_STATE_NONE is
    // only valid for plain EXCEPTION_DEFAULT. An earlier version of this file passed
    // THREAD_STATE_NONE here regardless, on the reasoning that this loop never reads old_state
    // (THREAD_STATE_NONE) and never asks the reply to modify it -- a state flavor is
    // installed anyway because a *stated* flavor of NONE with a state-carrying behavior is not
    // "no state, that's fine," it is invalid input the kernel silently declines to act on: no
    // exception is ever delivered, and it falls through to default handling (a plain BSD signal
    // to the target) as if no port were registered at all. The one-argument diagnosis cost real
    // time (see the task report); the fix is to pick a real flavor and simply not use the state
    // it carries, which is exactly what handleException() already does (old_state is unread,
    // new_stateCnt is always set to 0 so the reply never asks to modify it).
    //
    // Picked by architecture rather than hardcoded to this development machine's arm64, since
    // x86_64 is in scope from Milestone 3 onward. Both are full general-register state flavors --
    // the same ones MachBug::arch's SetSingleStep() reads/writes directly via
    // thread_get_state()/thread_set_state() on the reporting thread's own port, though that call is independent of
    // what flavor the exception PORT itself is configured to describe state as.
#if defined(__x86_64__)
    constexpr thread_state_flavor_t kExceptionPortStateFlavor = x86_THREAD_STATE64;
#elif defined(__arm64__) || defined(__aarch64__)
    constexpr thread_state_flavor_t kExceptionPortStateFlavor = ARM_THREAD_STATE64;
#else
#error "MachBug's exception loop needs a real thread-state flavor for this architecture"
#endif

    std::string describeMachMsg(const mach_msg_return_t mr)
    {
        std::string result = "mach_msg_return_t " + std::to_string(mr);
        if(const char* text = mach_error_string(mr))
        {
            result += " (";
            result += text;
            result += ")";
        }
        return result;
    }

    // Single-step support, used by StepInto(). This is a best-effort addition: no test in this
    // task's suite exercises it (the committed tests only ever Continue()), and the x86_64
    // branch has not been run on real hardware -- this development machine is arm64. Both
    // branches follow the standard pattern (arm64: MDSCR_EL1.SS via ARM_DEBUG_STATE64; x86_64:
    // EFLAGS.TF via x86_THREAD_STATE64), reading/writing the state directly on the reporting
    // thread port handleException() is handed, via a *different* state flavor
    // (ARM_DEBUG_STATE64/x86_THREAD_STATE64 here) than kExceptionPortStateFlavor configures the
    // exception message itself to carry -- the two are independent: this loop never reads the
    // old_state/new_state the message carries (handleException() ignores them and always
    // reports new_stateCnt = 0, meaning "unmodified"), so it does not matter that they are a
    // different flavor than what these functions ask thread_get_state()/thread_set_state() for
    // directly.
// The host's architecture, for the arch-layer calls below. The engine has no architecture query
// of its own at this level -- that is the C API's GetArch(), which also handles a translated
// target -- and this loop only ever touches the thread state of a target it is natively
// debugging, so the host's own architecture is the right answer here.
#if defined(__arm64__) || defined(__aarch64__)
    constexpr DbgArch kLoopArch = DbgArch_Arm64;
#elif defined(__x86_64__)
    constexpr DbgArch kLoopArch = DbgArch_X86_64;
#else
    constexpr DbgArch kLoopArch = DbgArch_Unknown;
#endif

    // Set only around exceptionLoop()'s own call into mach_exc_server(), and read only by
    // catch_mach_exception_raise_state_identity() (ExceptionServer.cpp) while that call is on
    // the stack -- MIG's dispatcher invokes the catch_* routine synchronously, on the same
    // thread, so a thread-local pointer identifies "which Debugger is this message for" without
    // needing a mutex-guarded port->Debugger* registry that every exception message would have
    // to take a lock to consult.
    thread_local MachBug::Debugger* tlsCurrentLoopDebugger = nullptr;
}

namespace MachBug
{
    Debugger* Debugger::Current()
    {
        return tlsCurrentLoopDebugger;
    }

    bool Debugger::Start()
    {
        if(!mProcess)
        {
            cbInternalError("Start() called with no launched process -- Init() must succeed first");
            return false;
        }

        if(mIsRunning.exchange(true, std::memory_order_acq_rel))
        {
            cbInternalError("Start() called while a debug loop is already running for this Debugger");
            return false;
        }

        // A fresh Init() launching a new child after a previous one's Start() ended (naturally,
        // or via Stop()) is the normal way to reuse a Debugger object, and every run of this loop
        // needs to begin without the previous one's bookkeeping still attached -- most pointedly
        // mStopRequested, which Stop() sets permanently and nothing previously cleared: a second
        // Start() after a Stop()'d first one would otherwise see it already true and return
        // (by way of exceptionLoop()'s own top-of-loop check) before installing a single port.
        mStopRequested.store(false, std::memory_order_release);
        mStopped.store(false, std::memory_order_release);
        mPausedByUser.store(false, std::memory_order_release);
        mSeenFirstStop = false;
        mStepArmed = false;

        // task_set_exception_ports() alone only ever catches an exception the target's own
        // execution triggers directly (a hardware fault, a trap instruction) -- it has no effect
        // on ordinary BSD signal delivery to the child. Without this call, a completely
        // well-behaved target (one that never faults) raises no exception in its entire life:
        // resuming it below via SIGCONT would just let it run straight through, with nothing to
        // report a first stop from. PT_ATTACHEXC is what changes that: it marks this task as a
        // Mach-exception-based tracer of the child (mirroring what PTRACE_TRACEME + the kernel's
        // automatic post-exec SIGTRAP does for ElfBug, just reached from the opposite side and
        // through the exception port instead of a bare signal) and, critically, makes the
        // kernel route every signal the child would otherwise receive -- including the very
        // SIGCONT this function sends a few lines down to undo Init()'s
        // POSIX_SPAWN_START_SUSPENDED -- through the exception port as EXC_SOFTWARE/
        // EXC_SOFT_SIGNAL instead of delivering it directly. That SIGCONT-turned-exception is
        // what becomes the first exception handleException() ever sees and reports through
        // cbSystemBreakpoint(): replying to it (Continue()) is what lets the original SIGCONT
        // actually take effect and the child run for the first time. Must happen before the
        // task_set_exception_ports() call below has any chance to matter, and while the child is
        // still suspended -- same reasoning as installing the exception ports themselves early.
        //
        // Skipped when Attach() (Debugger.cpp) already made this exact call: ptrace(2) does not
        // allow attaching to an already-attached pid a second time (EBUSY), and there is nothing
        // this second call would add -- Attach() already put mProcess->pid in the state this one
        // exists to reach (a Mach-exception tracee of this process), by the same call, before
        // ever returning to its own caller.
        if(!mAttachedViaPtrace && ptrace(PT_ATTACHEXC, mProcess->pid, nullptr, 0) != 0)
        {
            cbInternalError("ptrace(PT_ATTACHEXC) failed for pid " +
                             std::to_string(mProcess->pid) + ": " + std::string(strerror(errno)));
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        mach_port_t exceptionPort = MACH_PORT_NULL;
        kern_return_t kr = mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &exceptionPort);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("mach_port_allocate failed: " + Process::DescribeKernReturn(kr));
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        kr = mach_port_insert_right(mach_task_self(), exceptionPort, exceptionPort,
                                     MACH_MSG_TYPE_MAKE_SEND);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("mach_port_insert_right failed: " + Process::DescribeKernReturn(kr));
            mach_port_deallocate(mach_task_self(), exceptionPort);
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        // Installed while mProcess->task is still suspended (Init() left it that way via
        // POSIX_SPAWN_START_SUSPENDED) -- the child has executed no instruction of its own yet,
        // so there is no window in which it could raise an exception before a port exists to
        // catch it. EXCEPTION_STATE_IDENTITY gives both the thread port and its state in one
        // message; MACH_EXCEPTION_CODES is what makes the codes 64-bit, matching mach_exc.defs
        // over exc.defs (see MachBugMig.cmake). The flavor (kExceptionPortStateFlavor, above)
        // must be a real one -- EXCEPTION_STATE_IDENTITY is a state-carrying behavior, and
        // THREAD_STATE_NONE is only valid for EXCEPTION_DEFAULT; passing it here does not mean
        // "no state, that's fine," it means the kernel silently declines to deliver anything at
        // all. This loop still never reads the state the message carries (handleException() is
        // handed the thread's own port and calls thread_get_state()/thread_set_state() on it
        // directly when it needs to -- see MachBug::arch::SetSingleStep()) -- it just cannot ask for
        // *zero* state and expect delivery to still happen.
        kr = task_set_exception_ports(
            mProcess->task,
            kExceptionMask,
            exceptionPort,
            EXCEPTION_STATE_IDENTITY | MACH_EXCEPTION_CODES,
            kExceptionPortStateFlavor);
        if(kr != KERN_SUCCESS)
        {
            cbInternalError("task_set_exception_ports failed: " + Process::DescribeKernReturn(kr));
            mach_port_deallocate(mach_task_self(), exceptionPort);
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        mExceptionPort = exceptionPort;

        cbCreateProcessEvent(mProcess->pid);

        // Only now -- ports installed -- is it safe to let the child execute. This resumes the
        // exact suspension Task 3's Init() created and its regression test
        // (debugger_launch.cpp, "a suspended launch produces no output until resumed") proves is
        // real; that test resumes the same way, by hand, for the same reason this one does it
        // for real: SIGCONT is what actually undoes POSIX_SPAWN_START_SUSPENDED, not
        // task_resume() (there is no extra task-level suspension from posix_spawn to undo here;
        // Pause()'s task_suspend()/task_resume() pairing below is a separate, later mechanism).
        //
        // The same call does the equivalent job on the attach path (Debugger::Attach()): its own
        // PT_ATTACHEXC also stops the target via an actual SIGSTOP (ptrace(2)), which this SIGCONT
        // undoes exactly as it does POSIX_SPAWN_START_SUSPENDED's -- and since Attach() already
        // made pid a Mach-exception tracee of this process before this point, the kernel routes
        // this SIGCONT through mExceptionPort just installed above, the same way it does for a
        // launched child. Task 6 introduced Attach(); this call needed no change for it to work.
        if(kill(mProcess->pid, SIGCONT) != 0)
        {
            cbInternalError("SIGCONT failed to resume the suspended child: " +
                             std::string(strerror(errno)));
            mach_port_deallocate(mach_task_self(), mExceptionPort);
            mExceptionPort = MACH_PORT_NULL;
            mIsRunning.store(false, std::memory_order_release);
            return false;
        }

        exceptionLoop();

        if(mExceptionPort != MACH_PORT_NULL)
        {
            mach_port_deallocate(mach_task_self(), mExceptionPort);
            mExceptionPort = MACH_PORT_NULL;
        }

        mIsRunning.store(false, std::memory_order_release);
        return true;
    }

    void Debugger::exceptionLoop()
    {
        // Sized from mach_exc.h's own generated request/reply unions, not a guessed constant:
        // __Reply__mach_exception_raise_state_t's new_state[1296] alone is close to 5KB once the
        // other exception_raise_state* variants sharing this subsystem's message ID range are
        // accounted for. A hand-picked buffer (512 bytes, this file's first draft) is smaller
        // than that and risks MACH_RCV_TOO_LARGE -- which also destroys the oversized message,
        // rather than merely truncating it. This is not a theoretical case any more than it was
        // when this comment was first written: kExceptionPortStateFlavor (above) is a real state
        // flavor now, so the request genuinely does carry old_state (a modest few hundred bytes
        // for ARM_THREAD_STATE64/x86_THREAD_STATE64, well under the union's worst case) --
        // handleException() still ignores it and always reports new_stateCnt = 0, so the reply
        // itself carries none, but sizing this from the generated union rather than a guess means
        // neither direction depends on that staying true.
        union RequestMessage
        {
            mach_msg_header_t header;
            __RequestUnion__catch_mach_exc_subsystem body;
        };
        union ReplyMessage
        {
            mach_msg_header_t header;
            __ReplyUnion__catch_mach_exc_subsystem body;
        };

        for(;;)
        {
            if(mStopRequested.load(std::memory_order_acquire) &&
               !mStopped.load(std::memory_order_acquire))
            {
                // Stop() was called while the target is free-running -- no thread is parked in
                // handleException() to hand a decision to, so there is no reply to withhold or
                // send. Tear the child down directly, the same way Terminate() does.
                break;
            }

            RequestMessage request{};
            const mach_msg_return_t rcvResult = mach_msg(
                &request.header,
                MACH_RCV_MSG | MACH_RCV_TIMEOUT | MACH_RCV_INTERRUPT,
                0,
                sizeof(request),
                mExceptionPort,
                kExitPollIntervalMs,
                MACH_PORT_NULL);

            if(rcvResult == MACH_RCV_TIMED_OUT)
            {
                // No exception arrived in this slice. This is also the only place a *clean*
                // exit is ever noticed: exiting normally raises no Mach exception at all, so a
                // receive loop with nothing else in it would simply wait forever for a message
                // that is never coming. This process is the child's real parent (posix_spawn,
                // not an attach), so waitpid(WNOHANG) is a direct, reliable answer -- no
                // EXC_CRASH synthesis or dead-name/proc-exit notification needed for a debugger
                // that already owns the pid.
                //
                // waited > 0 alone is not enough, though: this pid was ptrace(PT_ATTACHEXC)'d
                // above (see Start()), and a traced child reports ordinary ptrace stops through
                // waitpid() too -- for instance while a thread is parked on an unanswered
                // exception reply, which is not a rare timing accident here, it is this loop's
                // own normal operation. Treating any waitpid() return as an exit, unconditionally,
                // computed a bogus exit code from a WIFSTOPPED status (WIFEXITED false ->
                // -WTERMSIG() of whatever bits happen to be set) and announced a live target as
                // dead. Process::IsRealExit() is the predicate that was missing.
                int status = 0;
                const pid_t waited = mProcess ? waitpid(mProcess->pid, &status, WNOHANG) : -1;
                if(waited > 0 && Process::IsRealExit(status))
                {
                    cbExitProcessEvent(Process::ExitCodeFromStatus(status));
                    break;
                }
                continue;
            }

            if(rcvResult == MACH_RCV_INTERRUPTED)
                continue;

            if(rcvResult != MACH_MSG_SUCCESS)
            {
                cbInternalError("mach_msg receive on the exception port failed: " +
                                 describeMachMsg(rcvResult));
                break;
            }

            ReplyMessage reply{};

            // handleException() (called synchronously from inside mach_exc_server(), via
            // catch_mach_exception_raise_state_identity() in ExceptionServer.cpp) does not
            // return until the user's decision is known -- see the class comment in Debugger.h.
            // Only once it does is `reply` complete and ready to send; that send is what
            // actually resumes the target thread.
            tlsCurrentLoopDebugger = this;
            const boolean_t handled = mach_exc_server(&request.header, &reply.header);
            tlsCurrentLoopDebugger = nullptr;

            if(!handled)
            {
                // A message arrived on this port that isn't one of mach_exc.defs' three
                // routines -- MIG's dispatcher leaves no valid reply to send in this case.
                cbInternalError("a message arrived on the exception port that mach_exc_server "
                                 "did not recognize");
                continue;
            }

            const mach_msg_return_t sendResult = mach_msg(
                &reply.header,
                MACH_SEND_MSG,
                reply.header.msgh_size,
                0,
                MACH_PORT_NULL,
                MACH_MSG_TIMEOUT_NONE,
                MACH_PORT_NULL);

            if(sendResult != MACH_MSG_SUCCESS)
            {
                cbInternalError("mach_msg send of the exception reply failed: " +
                                 describeMachMsg(sendResult));
                break;
            }

            if(mStopRequested.load(std::memory_order_acquire))
                break; // Stop() supplied the decision inside handleException(); the reply that
                       // resumed the reporting thread has gone out, so it is safe to kill now.

            // Only here, after the send succeeded and with no teardown pending, is the target
            // actually running again -- see cbResumed()'s comment in Debugger.h.
            cbResumed();
        }

        if(mStopRequested.load(std::memory_order_acquire) && mProcess)
        {
            // The target gets its own bytes back before this engine lets go of it. A detached
            // target still carrying a trap runs into it with no debugger listening and dies of a
            // SIGTRAP nobody asked for -- and until this was here, Stop() itself hung: the loop
            // was already gone, so that trap's exception had no one left to answer it.
            //
            // Usually a no-op since #107: a Stop answered at a stop already restored everything
            // above. This still covers the paths that never reach handleException at all -- a
            // free-running target, or one paused with task_suspend.
            mTeardownStage.store(TeardownStage::RestoringBreakpoints, std::memory_order_release);
            std::string restoreError;
            if(!mBreakpoints.RestoreAll(mProcess->task, kLoopArch, &restoreError))
                cbInternalError("could not remove this engine's breakpoints from the target "
                                 "before detaching: " + restoreError);

            // Process::DetachAndKill(), not a bare kill()+waitpid(): this pid is still
            // ptrace(PT_ATTACHEXC)'d (Start(), above), and this is the one place in this class
            // that is guaranteed to be reached with nobody left servicing the exception port --
            // the receive loop above has already broken out of. A plain SIGKILL sent here is
            // routed through that port exactly like any other signal and, unanswered, never takes
            // effect: not slower, not at all. Reproduced 3/3 with the documented sequence (Init ->
            // Start -> answer the first stop with Continue -> Stop) before this fix; see
            // Process::DetachAndKill()'s comment in Process.h.
            // The same release the Stop path above does, for the targets that never reach it:
            // one that was free-running when Stop() arrived, or paused with task_suspend. Both
            // still have this port registered, and an exception raised into a loop that has
            // gone blocks the thread that raised it.
            task_set_exception_ports(mProcess->task, kExceptionMask, MACH_PORT_NULL,
                                     EXCEPTION_STATE_IDENTITY | MACH_EXCEPTION_CODES,
                                     kExceptionPortStateFlavor);

            mTeardownStage.store(TeardownStage::Detaching, std::memory_order_release);
            Process::DetachAndKill(mProcess->pid, nullptr);
        }

        mTeardownStage.store(TeardownStage::Finished, std::memory_order_release);
    }

    const char* Debugger::TeardownStageName() const
    {
        switch(mTeardownStage.load(std::memory_order_acquire))
        {
        case TeardownStage::Running:               return "still in the receive loop";
        case TeardownStage::RestoringBreakpoints:  return "restoring the target's bytes";
        case TeardownStage::Detaching:             return "detaching and killing the target";
        case TeardownStage::Finished:              return "finished";
        }
        return "unknown";
    }

    kern_return_t Debugger::handleException(const mach_port_t thread, const exception_type_t exception,
                                             const mach_exception_data_t code,
                                             const mach_msg_type_number_t codeCnt)
    {
        // This call IS the stop. Nothing resumes the reporting thread until this function
        // returns -- MIG's generated server sends the reply that does so only after this
        // callback comes back to it. So the classification/callback below must happen before
        // parking, and the park (the mCmdCv.wait() further down) is the entire reason the
        // target does not run again until Continue()/StepInto()/Stop() says so.

        // A step is complete when a step was armed AND this exception is the trap a step
        // produces. Testing mStepArmed alone -- which is what this did until milestone 4 --
        // reports the *next* exception of any kind as a completed step: on x86-64 a signal
        // passthrough arrived first and was announced as a step whose program counter had not
        // moved, which is a lie about the target rather than a missed event (issue #97).
        //
        // mStepArmed survives an exception that is not the step: the step may still land later,
        // and forgetting it would leave the trap armed with nothing waiting for it.
        // Every stop is a chance to see what the target's thread list has done since the last
        // one -- and the only chance, since nothing notifies a debugger of a thread's birth.
        // The same is true of its modules, and for the same reason.
        refreshThreads();
        refreshModules();

        bool wasStepCompletion = mStepArmed &&
            arch::IsSingleStepTrap(kLoopArch, exception, code, codeCnt);

        // MEASURED, and the reason a watchpoint could not be stepped off at all until this
        // existed: answering a watchpoint's exception queues a SIGTRAP for the thread, which
        // arrives as EXC_SOFTWARE/EXC_SOFT_SIGNAL/SIGTRAP *before* the armed step has run a
        // single instruction. It is shaped exactly like the step completion of a software
        // breakpoint (task 3 measured that one arriving the same way), so the engine counted it
        // as the step, re-armed the watchpoint, and resumed a thread that had executed nothing:
        //
        //     exception=6 code0=0x102 code1=<the global>     the watchpoint
        //     exception=5 code0=0x10003 code1=0x5            SIGTRAP, stepArmed=1, pc unchanged
        //     exception=6 code0=0x102 code1=<the global>     the same store, forever
        //
        // What separates the two is the program counter: a step that completed moved it, and
        // this one did not. So a trap that arrives at the address the cycle started from is the
        // leftover signal rather than the step -- suppressed here (PT_THUPDATE works now, where
        // it was refused as EBUSY at the watchpoint stop itself, because only now is a signal
        // actually pending), and the step is left armed to complete on its own.
        if(wasStepCompletion && mSteppingOverBreakpoint && mSteppingOffFromPc != 0)
        {
            DbgRegisters regs{};
            std::string readError;
            if(arch::Read(kLoopArch, thread, &regs, &readError))
            {
                const uint64_t pc =
                    kLoopArch == DbgArch_Arm64 ? regs.arm64.pc : regs.x86_64.rip;
                if(pc == mSteppingOffFromPc)
                {
                    suppressPendingSignal(thread, "the trap the stop itself queued");
                    return KERN_SUCCESS;
                }
            }
        }
        if(wasStepCompletion)
            mStepArmed = false;
        if(wasStepCompletion)
        {
            // Disarmed through the arch layer (arch/Arm64.cpp, arch/X86_64.cpp) rather than here;
            // re-armed below only if StepInto() is chosen again.
            std::string stepError;
            if(!arch::SetSingleStep(kLoopArch, thread, false, &stepError))
                cbInternalError(stepError);
        }

        // The second half of the restore-step-re-arm cycle (spec section 6). Getting off a
        // software breakpoint means taking its trap out, advancing one instruction, and putting
        // the trap back -- and this is where the step that did the advancing lands.
        //
        // Reported to the caller only if they asked for a step. A Continue() that happened to
        // start on a breakpoint must not look like a step to whoever is watching: the step is
        // this engine's own machinery for leaving an address it had patched.
        if(mSteppingOverBreakpoint && wasStepCompletion)
        {
            mSteppingOverBreakpoint = false;

            suppressPendingSignal(thread, "the step");

            std::string rearmError;
            if(mStoppedAtBreakpoint != 0 && mProcess &&
               !mBreakpoints.Arm(mProcess->task, kLoopArch, mStoppedAtBreakpoint, &rearmError))
            {
                // Loud, because the alternative is a breakpoint the user still sees in the list
                // and the target no longer carries -- the failure mode hardest to notice.
                cbInternalError("could not re-arm the breakpoint after stepping off it: " +
                                 rearmError);
            }
            mStoppedAtBreakpoint = 0;
            mSteppingOffFromPc = 0;

            if(!mStepWasRequested)
                return KERN_SUCCESS;   // resume, silently: nobody asked to be told about this
            mStepWasRequested = false;
        }

        // The other half of the same measurement: answering an EXC_BREAKPOINT queues a SIGTRAP
        // for the thread, and it arrives here as a passthrough after the reply has gone out.
        // While a step is armed that passthrough IS how a step off a software breakpoint
        // completes (task 3 measured that), so those two cases are handled above and this one
        // catches what is left: a trap this engine caused, whose signal the target never asked
        // for and must not be stopped by. Answered and swallowed rather than reported -- an
        // unexplained EXC_SOFTWARE parked the target after every watchpoint hit until this
        // existed.
        constexpr int32_t kExcSoftSignalCode = 0x10003;
        const bool queuedTrapArrived =
            mQueuedSigTrapExpected && !mStepArmed && exception == EXC_SOFTWARE &&
            codeCnt >= 2 && code[0] == kExcSoftSignalCode && code[1] == SIGTRAP;
        if(queuedTrapArrived)
        {
            mQueuedSigTrapExpected = false;
            suppressPendingSignal(thread, "the trap this engine caused");
            return KERN_SUCCESS;
        }

        // Set for the reply this call is about to send, and only for the exception kind that was
        // measured to queue one.
        mQueuedSigTrapExpected = exception == EXC_BREAKPOINT;

        // EXC_SOFTWARE with code[0] == EXC_SOFT_SIGNAL is how PT_ATTACHEXC (Start(), above)
        // routes an ordinary BSD signal through this port instead of delivering it directly;
        // code[1] carries the signal number. The very first exception this loop ever sees is
        // deliberately treated as the target's first stop regardless of what kind it is (see the
        // !mSeenFirstStop branch, below) -- in practice that first one always is this case, since
        // it is the SIGCONT Start() sends to undo POSIX_SPAWN_START_SUSPENDED, turned into an
        // exception by the same PT_ATTACHEXC. A *second* SIGCONT has also been observed arriving
        // later (roughly one run in ten), and unlike the first one, nothing in this milestone's
        // contract gives a caller any way to have asked to be notified of it -- routing it to
        // cbException() and parking the way a real debug exception parks left the reporting
        // thread waiting for a Continue() call nobody knew to make, IsStopped() still reporting
        // false throughout, and the target hung forever with the reply withheld.
        //
        // The fix is deliberately narrow: only SIGCONT is absorbed, and only code[1] == SIGCONT
        // decides that, not code[0] alone. An earlier version of this check matched any
        // EXC_SOFT_SIGNAL regardless of which signal, which silently passed through *every*
        // signal-passthrough exception -- a target's own abort() (SIGABRT) or a user's SIGINT
        // would have been swallowed exactly like SIGCONT, with no cbException() call, no stop, and
        // no way for a caller to ever know it happened. That is worse than the hang it was fixing:
        // a hang is at least visible. SIGCONT is the one signal this loop's own machinery can
        // cause to arrive here more than once and the only one that did not originate from the
        // target or its user in the first place -- it originated from this debugger's own resume
        // handshake -- so it is the only one with a defensible reason to be answered without ever
        // being reported. Every other signal-passthrough exception now falls through to the
        // ordinary cbException() path below, exactly as any other exception this loop does not
        // have more specific handling for yet.
        constexpr int32_t kExcSoftSignal = 0x10003; // EXC_SOFT_SIGNAL
        const bool isSignalPassthrough =
            exception == EXC_SOFTWARE && codeCnt >= 2 && code[0] == kExcSoftSignal &&
            code[1] == SIGCONT;

        if(!wasStepCompletion && mSeenFirstStop && isSignalPassthrough)
            return KERN_SUCCESS;

        {
            std::lock_guard<std::mutex> lock(mCmdMutex);
            // Recorded before mStopped, not after: IsStopped() going true is what tells another
            // thread there are registers to read, so the thread they belong to has to be
            // readable by the time that is observable.
            mStoppedThread.store(thread, std::memory_order_release);
            mStopped.store(true, std::memory_order_release);
            mPendingCommand = Command::None;
        }

        // Is this one of ours? Identified by address rather than by exception code: both
        // architectures report a software trap as EXC_BREAKPOINT, and the accompanying code says
        // which *kind* of debug event it was, never which of this engine's breakpoints. Only the
        // table knows that.
        //
        // A watchpoint is the exception to that, and has to be, because the address it stopped
        // on is not the program counter: it is the data address the instruction touched. The
        // architecture layer is what knows where to find it -- in code[1] on arm64, in the
        // thread's own DR6/DR7 on x86-64 -- and a watchpoint hit matched against the program
        // counter finds nothing at all.
        uint64_t hitBreakpoint = 0;
        const arch::DebugTrap debugTrap = !wasStepCompletion && mSeenFirstStop
            ? arch::DecodeDebugTrap(kLoopArch, thread, exception, code, codeCnt)
            : arch::DebugTrap{};

        if(debugTrap.isWatchpoint)
        {
            // MEASURED, and it costs the target its progress if it is not done: answering a
            // watchpoint exception with KERN_SUCCESS leaves a SIGTRAP pending for the thread,
            // which arrives immediately afterwards as EXC_SOFTWARE/EXC_SOFT_SIGNAL/SIGTRAP. With
            // a step armed -- which the step-off cycle always has here -- that passthrough is
            // indistinguishable from a step completion, so the engine re-armed the watchpoint on
            // a thread that had not executed anything, and the target sat on the same
            // instruction forever: pc unchanged and the watched value never incremented across
            // repeated hits.
            //
            // Task 3 found the kernel refuses this for a software breakpoint trap (EBUSY, no
            // signal pending). A watchpoint is the other case: there is one, and it is this
            // engine's own machinery rather than anything the target asked for.
            const auto entry = mBreakpoints.Find(debugTrap.dataAddress);
            if(entry && entry->armed)
                hitBreakpoint = debugTrap.dataAddress;
            // No program-counter rewind here, unlike a software trap: nothing was patched, and
            // the pc points at the instruction that made the access rather than at anything the
            // engine put there.
        }
        else if(!wasStepCompletion && exception == EXC_BREAKPOINT && mSeenFirstStop)
        {
            DbgRegisters regs{};
            std::string readError;
            if(arch::Read(kLoopArch, thread, &regs, &readError))
            {
                const uint64_t pc = kLoopArch == DbgArch_Arm64 ? regs.arm64.pc : regs.x86_64.rip;

                // Where the program counter is relative to the breakpoint depends on which kind
                // stopped the target, and the kind is only known once a match is found -- so both
                // candidates are tried, hardware first. A hardware breakpoint faults *before* the
                // instruction runs, so the pc is the address itself; a software trap on x86-64 has
                // already executed its INT3 byte, so the pc is one past it. Applying the software
                // fixup to a hardware hit looks up an address one byte before the breakpoint,
                // which matches nothing and reports a hit as an unexplained exception. On arm64
                // the fixup is zero and the two candidates are the same address.
                uint32_t fixup = 0;
                auto entry = mBreakpoints.Find(pc);
                if(!entry || !entry->armed || entry->kind == DbgBreakpointKind_Software)
                {
                    fixup = arch::PcFixupAfterTrap(kLoopArch);
                    entry = mBreakpoints.Find(pc - fixup);
                }

                const uint64_t candidate = pc - fixup;
                if(entry && entry->armed)
                {
                    hitBreakpoint = candidate;

                    // Rewound before anyone is told, so the caller sees the address it asked for
                    // and a resume re-executes the instruction the trap replaced. On arm64 the
                    // fixup is zero and this does nothing; on x86-64 it is the difference between
                    // resuming correctly and resuming one byte into an instruction.
                    if(fixup != 0)
                    {
                        std::string writeError;
                        if(!arch::Write(kLoopArch, thread, "rip", candidate, &writeError))
                            cbInternalError("could not rewind the program counter onto the "
                                             "breakpoint: " + writeError);
                    }
                }
            }
            else
            {
                cbInternalError(readError);
            }
        }

        if(hitBreakpoint != 0)
        {
            mStoppedAtBreakpoint = hitBreakpoint;
            cbBreakpoint(hitBreakpoint);
        }
        else if(wasStepCompletion)
        {
            cbStep();
        }
        else if(!mSeenFirstStop)
        {
            mSeenFirstStop = true;
            cbSystemBreakpoint();
        }
        else
        {
            const uint64_t address = codeCnt >= 2 ? static_cast<uint64_t>(code[1]) : 0;
            cbException(static_cast<uint32_t>(exception), address);
        }

        Command decision;
        {
            std::unique_lock<std::mutex> lock(mCmdMutex);
            mCmdCv.wait(lock, [this] {
                return mPendingCommand != Command::None ||
                       mStopRequested.load(std::memory_order_acquire);
            });

            decision = mPendingCommand != Command::None ? mPendingCommand : Command::Stop;
            mPendingCommand = Command::None;
            mStopped.store(false, std::memory_order_release);
            // Cleared with the stop it belonged to: a caller that reads registers from a thread
            // that is running again gets a torn answer, and no error to tell it so.
            mStoppedThread.store(MACH_PORT_NULL, std::memory_order_release);
        }

        // Leaving a breakpoint's own address means the trap cannot be there when the target
        // resumes, or it traps again immediately on the instruction it never got to execute.
        // Take it out, step once, and the completion above puts it back.
        if(mStoppedAtBreakpoint != 0 &&
           (decision == Command::Continue || decision == Command::StepInto))
        {
            std::string cycleError;
            const bool disarmed = mProcess &&
                mBreakpoints.Disarm(mProcess->task, kLoopArch, mStoppedAtBreakpoint, &cycleError);
            if(disarmed && arch::SetSingleStep(kLoopArch, thread, true, &cycleError))
            {
                // Where the cycle started, so a trap that has not moved off it can be recognised
                // as not being the step. Read here rather than remembered from the stop, because
                // a caller may have written the program counter while the target was parked.
                DbgRegisters regs{};
                std::string readError;
                mSteppingOffFromPc = arch::Read(kLoopArch, thread, &regs, &readError)
                    ? (kLoopArch == DbgArch_Arm64 ? regs.arm64.pc : regs.x86_64.rip)
                    : 0;

                mStepArmed = true;
                mSteppingOverBreakpoint = true;
                mStepWasRequested = decision == Command::StepInto;
                return KERN_SUCCESS;
            }

            // The half that did work has to be undone, or the cycle leaves the target without a
            // breakpoint the caller still believes in -- the quietest way to lose one. Arming
            // again cannot be assumed to succeed either, so its own failure is reported rather
            // than swallowed by the failure that caused it.
            if(disarmed && mProcess)
            {
                std::string rearmError;
                if(!mBreakpoints.Arm(mProcess->task, kLoopArch, mStoppedAtBreakpoint, &rearmError))
                    cbInternalError("could not put the breakpoint back after failing to step off "
                                     "it: " + rearmError);
            }

            // Resumed anyway, with the reason said out loud: the target will trap here again
            // immediately, which is visible and recoverable, while parking it forever is neither.
            cbInternalError("could not step off the breakpoint: " + cycleError);
            mStoppedAtBreakpoint = 0;
        }

        if(decision == Command::Stop)
        {
            // Before the reply, not after it. Returning from here resumes the reporting thread,
            // and if the stop was on a breakpoint it resumes onto the trap it is standing on --
            // raising an exception at a port whose loop is, by then, on its way out. Nobody
            // answers it, the thread stays blocked in the kernel, and the kill that follows is
            // dealing with a process in that state. The teardown below did this restore, but
            // one reply too late to prevent the window (issue #107).
            std::string restoreError;
            if(mProcess && !mBreakpoints.RestoreAll(mProcess->task, kLoopArch, &restoreError))
                cbInternalError("could not remove this engine's breakpoints before letting the "
                                 "target go: " + restoreError);

            // MEASURED, and the reason the previous attempt at this was not enough: answering a
            // debug exception queues a SIGTRAP for the thread (issue #109), and with this port
            // still registered that signal comes back here as one more exception -- to a loop
            // that has already left. The thread then sits in the kernel waiting for a reply
            // nobody will send, and the ptrace detach and kill that follow are dealing with a
            // process in that state. The harness's guard caught exactly that and named the
            // stage: "detaching and killing the target", with no sign of
            // WaitForRealExit()'s own bound having elapsed.
            //
            // Handing the mask back before the reply is what closes it: the straggler signal
            // gets default handling on a process this engine is about to kill anyway.
            if(mProcess)
            {
                const kern_return_t released = task_set_exception_ports(
                    mProcess->task, kExceptionMask, MACH_PORT_NULL,
                    EXCEPTION_STATE_IDENTITY | MACH_EXCEPTION_CODES, kExceptionPortStateFlavor);
                if(released != KERN_SUCCESS)
                    cbInternalError("could not hand the exception ports back before detaching: " +
                                     Process::DescribeKernReturn(released));
            }

            // The step this engine armed to get off a breakpoint goes with them, for the same
            // reason: a target resumed with the trap flag still set traps again immediately.
            if(mStepArmed)
            {
                std::string stepError;
                if(!arch::SetSingleStep(kLoopArch, thread, false, &stepError))
                    cbInternalError(stepError);
                mStepArmed = false;
            }
        }

        if(decision == Command::StepInto)
        {
            std::string armError;
            if(arch::SetSingleStep(kLoopArch, thread, true, &armError))
            {
                mStepArmed = true;
            }
            else
            {
                cbInternalError("StepInto: failed to arm single-step on the reporting thread; "
                                 "continuing normally instead");
            }
        }

        // Returning KERN_SUCCESS is what tells the kernel this exception was handled and the
        // reporting thread should resume -- true for Continue and StepInto alike; the only
        // difference between them is whether SetSingleStep() armed the trap flag just above, not
        // the return code. Stop() takes the same return here (the thread must still be let go,
        // its message answered) and is instead handled by exceptionLoop() killing the child once
        // this reply has gone out; see its comment.
        return KERN_SUCCESS;
    }

    void Debugger::Continue()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);

        // Independent ifs, not if/else: mStopped (a parked exception reply) and mPausedByUser (a
        // direct task_suspend()) are two separate reasons the target might not be running, and --
        // under a race Pause() used to allow (see its own comment) -- could in principle both be
        // true at once. A single Continue() call clears whichever of them apply, rather than
        // leaving the other stranded until a second call happens to be made because IsStopped()
        // still (correctly) said so.
        if(mStopped.load(std::memory_order_acquire))
        {
            mPendingCommand = Command::Continue;
            mCmdCv.notify_all();
        }
        if(mPausedByUser.exchange(false, std::memory_order_acq_rel) && mProcess)
        {
            // Nothing is parked in handleException() -- the target was free-running when
            // Pause() task_suspended it directly, so undo that the same way, with task_resume().
            task_resume(mProcess->task);
        }
    }

    void Debugger::StepInto()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        if(mStopped.load(std::memory_order_acquire))
        {
            mPendingCommand = Command::StepInto;
            mCmdCv.notify_all();
        }
        // Nothing to single-step from if the target is free-running (Pause()'d or otherwise) --
        // there is no thread parked in handleException() to arm a step in.
    }

    void Debugger::Pause()
    {
        if(!mProcess)
            return;

        // The whole check-then-act sequence below holds mCmdMutex so it cannot interleave with
        // handleException() setting mStopped=true (which happens under the same lock): either
        // this runs first (sees mStopped false, may go on to task_suspend()) or the exception's
        // own mStopped=true happens first (this then sees it and returns). Checking mStopped
        // outside this lock, as an earlier version of this function did, raced exactly that
        // transition: Pause() could read false, then task_suspend() a target that had, in the
        // meantime, already become parked at a genuine exception -- suspending an
        // already-stopped task and setting mPausedByUser regardless.
        std::lock_guard<std::mutex> lock(mCmdMutex);

        if(mPausedByUser.load(std::memory_order_acquire))
            return; // already paused -- idempotent, so repeated Pause() calls cannot leave
                     // task_suspend()'s internal count deeper than the one task_resume() a
                     // Continue() call will later issue; the alternative (suspending again on
                     // every call) is exactly the "Pause(); Pause(); Continue();" bug this
                     // guards against: two suspends, only one resume, permanently stuck.

        if(mStopped.load(std::memory_order_acquire))
            return; // already stopped at an exception; nothing more to pause

        if(task_suspend(mProcess->task) != KERN_SUCCESS)
            return;

        mPausedByUser.store(true, std::memory_order_release);

        // This is a stop, so the thread list gets its look -- and this is the one stop the
        // exception loop never hears about, which is why the call is here as well as there. The
        // callbacks it may fire land on the caller's thread rather than the loop's; see
        // cbThreadCreate's comment in Debugger.h for why that is written down rather than
        // hidden. Called with mCmdMutex held, which is safe because neither refresh takes a
        // lock of its own or re-enters anything that takes this one -- they touch mThreads,
        // mModules and the target's port.
        refreshThreads();
        refreshModules();
    }

    void Debugger::Stop()
    {
        std::lock_guard<std::mutex> lock(mCmdMutex);
        mStopRequested.store(true, std::memory_order_release);
        if(mStopped.load(std::memory_order_acquire))
            mPendingCommand = Command::Stop;
        mCmdCv.notify_all();
    }

    bool Debugger::IsStopped() const
    {
        return mStopped.load(std::memory_order_acquire) ||
               mPausedByUser.load(std::memory_order_acquire);
    }

    bool Debugger::IsRunning() const
    {
        return mIsRunning.load(std::memory_order_acquire);
    }

    void Debugger::suppressPendingSignal(const mach_port_t thread, const char* what)
    {
        if(!mProcess)
            return;

        // MEASURED. A step that this engine armed reaches the target as a passed-through SIGTRAP
        // as well as an exception, and answering the exception with KERN_SUCCESS does not stop
        // the delivery: the fixture died with ExitProcess(code=-5) until this call existed.
        //
        // Only for that case. Calling it for a raw breakpoint trap was tried and the kernel
        // refused with EBUSY ("Resource busy"): PT_THUPDATE decides the fate of a signal that is
        // pending for the thread, and an EXC_BREAKPOINT this engine answers has none.
        //
        // PT_THUPDATE decides a passed-through signal's fate: its third argument is the thread
        // port and its fourth is the signal to deliver, so zero means deliver nothing. Every trap
        // this engine set is its own machinery; the target never asked for it and must not see it.
        // EBUSY is not a failure here, and reporting it as one was noise: the kernel answers
        // that way when the thread has no pending signal at all -- which is exactly the state
        // this call is trying to reach. It happens whenever the trap being answered has not
        // queued its signal yet, and the signal then arrives as its own exception, which the
        // caller above absorbs.
        errno = 0;
        if(ptrace(PT_THUPDATE, mProcess->pid,
                  reinterpret_cast<caddr_t>(static_cast<uintptr_t>(thread)), 0) == -1 &&
           errno != 0 && errno != EBUSY)
        {
            cbInternalError(std::string("could not suppress the signal for ") + what + ": " +
                             std::strerror(errno));
        }
    }

    Breakpoints& Debugger::BreakpointTable()
    {
        return mBreakpoints;
    }

    std::size_t Debugger::ThreadCount() const
    {
        return mThreads.Known().size();
    }

    void Debugger::refreshModules()
    {
        if(!mProcess)
            return;

        const Modules::Change change = mModules.Refresh(mProcess->task);
        for(const Modules::Image& image : change.appeared)
            cbLoadModule(image.loadAddress, image.path);
        for(const Modules::Image& image : change.disappeared)
            cbUnloadModule(image.loadAddress);
    }

    std::vector<Modules::Image> Debugger::LoadedModules() const
    {
        return mModules.Known();
    }

    std::size_t Debugger::ModuleCount() const
    {
        return mModules.Known().size();
    }

    void Debugger::refreshThreads()
    {
        if(!mProcess)
            return;

        const Threads::Change change = mThreads.Refresh(mProcess->task);
        for(const uint64_t threadId : change.appeared)
        {
            // Before the callback, not after: a caller told about a new thread may go straight
            // to reading its state, and the breakpoints this engine promised are part of that
            // state. A thread born after a hardware breakpoint was set carries none of it until
            // this write happens.
            std::string applyError;
            if(!mBreakpoints.ApplyToThread(kLoopArch, mThreads.PortFor(threadId), &applyError))
                cbInternalError("could not arm the hardware breakpoints on a new thread: " +
                                 applyError);
            cbThreadCreate(threadId);
        }
        for(const uint64_t threadId : change.disappeared)
            cbThreadExit(threadId);
    }

    mach_port_t Debugger::StoppedThread() const
    {
        return mStoppedThread.load(std::memory_order_acquire);
    }

    mach_port_t Debugger::ResolveThread(const uint64_t threadId) const
    {
        if(threadId == 0)
            return StoppedThread();

        // A system thread id, not a port name. Milestone 4 measured why that distinction has to
        // exist: task_threads mints fresh send rights on every call, so a port name identifies a
        // thread only until the next poll -- naming threads that way reported a three-thread
        // target as three creations and handed back ids that no longer resolved. Threads holds
        // one right per live thread and maps the stable id onto it.
        return mThreads.PortFor(threadId);
    }

    void Debugger::cbCreateProcessEvent(pid_t) {}
    void Debugger::cbExitProcessEvent(int) {}
    void Debugger::cbSystemBreakpoint() {}
    void Debugger::cbBreakpoint(uint64_t) {}
    void Debugger::cbLoadModule(uint64_t, const std::string&) {}
    void Debugger::cbUnloadModule(uint64_t) {}
    void Debugger::cbThreadCreate(uint64_t) {}
    void Debugger::cbThreadExit(uint64_t) {}
    void Debugger::cbResumed() {}
    void Debugger::cbStep() {}
    void Debugger::cbException(uint32_t, uint64_t) {}
}
