# Generates the Mach exception server from the SDK's mach_exc.defs and wraps
# it in a target other code can link: machbug_mig.
#
# mach_exc.defs rather than exc.defs: the mach_ variant carries 64-bit
# exception codes, which MACH_EXCEPTION_CODES requires and arm64 needs.
#
# WHY THE GENERATION RUNS ON EVERY BUILD, IN A SCRIPT, INSTEAD OF BEING A
# CONFIGURE-TIME RULE: this file used to resolve the SDK once with `xcrun
# --show-sdk-path` at configure time and bake that path into an
# add_custom_command whose DEPENDS covered the .defs file and the mig binary.
# A configured build tree that outlived an SDK change then kept generating
# against the recorded path -- and the generated code is the wire format of
# every exception message this debugger receives, so a stale server is not a
# cosmetic problem. Neither dependency closed that hole:
#   - The .defs path is only re-read if its *mtime* changes, and it is the
#     path resolved at configure time, not the path xcrun would resolve now.
#     Two SDKs installed side by side each have their own copy, so switching
#     between them (xcode-select, a new Xcode, SDKROOT in the environment)
#     changes which file matters without touching the one being watched.
#   - mig resolves to /usr/bin/mig, the Command Line Tools shim, whose mtime
#     tracks the OS/CLT install rather than the Xcode.app being pointed at.
#     An Xcode-only update leaves it untouched, so "a newer mig reruns this"
#     did not hold either.
# MachBugMigGenerate.cmake therefore resolves the SDK at build time and
# rewrites the outputs only when the generated bytes differ, so the recurring
# cost is one mig invocation per build and nothing downstream recompiles
# unless the wire format genuinely moved.
find_program(MACHBUG_MIG mig REQUIRED)

set(MACHBUG_MIG_DIR "${CMAKE_CURRENT_BINARY_DIR}/mig")
file(MAKE_DIRECTORY "${MACHBUG_MIG_DIR}")

# Configure-time sanity check only -- deliberately not stored and not passed to the
# generation below, which resolves the SDK itself. Its whole job is to fail here, with a
# clear message, on a machine that could never generate the server at all, rather than
# leaving that to the first build.
execute_process(
    COMMAND xcrun --show-sdk-path
    OUTPUT_VARIABLE _sdk_path_at_configure_time
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT EXISTS "${_sdk_path_at_configure_time}/usr/include/mach/mach_exc.defs")
    message(FATAL_ERROR
        "mach_exc.defs not found under the SDK xcrun resolves "
        "(${_sdk_path_at_configure_time}); the Mach exception server cannot be generated.")
endif()

# A custom target, not a custom command: custom commands run only when their declared
# inputs look newer than their outputs, which is exactly the check that cannot see an SDK
# swap. A target with no outputs of its own always runs, and the script it runs is what
# decides whether anything needs rewriting.
add_custom_target(machbug_mig_generate ALL
    COMMAND "${CMAKE_COMMAND}"
            -DMACHBUG_MIG=${MACHBUG_MIG}
            -DMACHBUG_MIG_DIR=${MACHBUG_MIG_DIR}
            -P "${CMAKE_CURRENT_LIST_DIR}/MachBugMigGenerate.cmake"
    BYPRODUCTS "${MACHBUG_MIG_DIR}/mach_excServer.c"
               "${MACHBUG_MIG_DIR}/mach_exc.h"
    COMMENT "Generating the Mach exception server from mach_exc.defs"
    VERBATIM
)

# GENERATED, so configuring a fresh build tree does not fail on a source file that only
# exists once machbug_mig_generate has run.
set_source_files_properties("${MACHBUG_MIG_DIR}/mach_excServer.c" PROPERTIES GENERATED TRUE)

# The generated server declares three catch_mach_exception_raise* symbols but
# does not implement any of them -- that is what makes it a *server* someone
# else fills in, not a working exception loop. Without a definition for at
# least all three, nothing that references mach_exc_server can link. See
# MachBugMigStubs.c for what is provided permanently versus provided only
# until the real debugger loop exists.
add_library(machbug_mig STATIC
    "${MACHBUG_MIG_DIR}/mach_excServer.c"
    "${CMAKE_CURRENT_LIST_DIR}/MachBugMigStubs.c"
)
target_include_directories(machbug_mig PUBLIC "${MACHBUG_MIG_DIR}")

# Target-level ordering is what guarantees the generated sources exist (and are current)
# before anything compiles them. It is also the only ordering available here: the files are
# byproducts of a target rather than outputs of a command, so there is no file-level edge
# for the build system to infer.
add_dependencies(machbug_mig machbug_mig_generate)
